services:
    nextjs-app:
        image: node
        volumes:
            - .:/usr/src/app
        container_name: nextjs-app
        restart: always
        ports:
            - '80:80'
            - '5555:5555'
        environment:
            - DATABASE_URL=${DATABASE_URL}
        working_dir: /usr/src/app
        command: sh -c "npm install && npm run dev -- -p 80"