services:
    nextjs-app:
        image: node
        volumes:
            - .:/usr/src/app
        container_name: nextjs-app
        restart: always
        ports:
            - '80:80'
            - '5555:5555'
        environment:
            POSTGRES_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@nextjs-postgres:5432/${POSTGRES_DATABASE}"
        working_dir: /usr/src/app
        command: sh -c "npm install && npm run dev -- -p 80"
        depends_on:
            - nextjs-postgres
    nextjs-postgres:
        image: postgres
        container_name: nextjs-postgres
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DATABASE}
        ports:
            - '5432:5432'