services:
    nextjs-app:
        image: node
        volumes:
            - .:/usr/src/app
        container_name: nextjs-app
        restart: always
        ports:
            - '3000:3000'
            - '5555:5555'
        environment:
            - DATABASE_URL=postgresql://myuser:mypassword@postgres_container:5432/mydb?schema=public
        working_dir: /usr/src/app
        command: sh -c "npm install && npm run dev"